version: "3"
services:
  bot:
    image: kangaroux/etternabot
    build:
      context: .
    restart: always
    environment:
      - BOT_TOKEN
      - ETTERNA_API_KEY
      - POSTGRES_USER=${POSTGRES_USER:-etterna}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-etterna}
      - DATABASE_HOST=db
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-etterna}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-etterna}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql"
volumes:
  dbdata: