version: "3"
services:
  bot:
    image: kangaroux/etternabot
    build:
      context: .
    restart: always
    environment:
      - BOT_TOKEN
      - ETTERNA_API_KEY
      - POSTGRES_USER=${POSTGRES_USER:-etterna}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-etterna}
      - DATABASE_HOST=db
    depends_on:
      - db
    networks:
      net: {}
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-etterna}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-etterna}
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql"
    networks:
      net: {}
volumes:
  dbdata:
networks:
  net: